// This file is automatically generated by Xamarin.Insights - do not modify
namespace MalaysiaAPI
{
	class XamarinInsights
	{
		public const string ApiKey = "b39e12332805647636f2cd803d2a40b54d7cfa5d";
	}
}